## Numpy Array Operations

In [2]:
import numpy as np

In [ ]:

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing" , arr[2:7])
print("With step" , arr[1:8:2])
print("negative Indexing" , arr[-3])

Basic Slicing [3 4 5 6 7]
With step [2 4 6 8]
negative Indexing 8


In [5]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element" , arr_2d[1,2])
print("Entire Row", arr_2d[1])
print("Entire Col", arr_2d[:,1])

Specific element 6
Entire Row [4 5 6]
Entire Col [2 5 8]


## Sorting

In [9]:
unsorted = ([3,4,2,1,6,7,10,5])
print("Sorted array" , np.sort(unsorted))

arr_2d = np.array([[3,1] , [1,2] , [2,3]])
print("Sorted 2d_matrix by column" , np.sort(arr_2d , axis=0))
print("Sorted 2d_matrix by row" , np.sort(arr_2d , axis=1))

Sorted array [ 1  2  3  4  5  6  7 10]
Sorted 2d_matrix by column [[1 1]
 [2 2]
 [3 3]]
Sorted 2d_matrix by row [[1 3]
 [1 2]
 [2 3]]


## Filter

In [4]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even = numbers[numbers %2 == 0]
print("Even Numbers" , even)


Even Numbers [ 2  4  6  8 10]


## Filter with Mask

In [5]:
mask = numbers > 5
print("Numbers greater than 5" , numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


 ## Fancy indexing vs np.where()

In [6]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
print(where_result)
print(numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]


In [7]:
condition_array = np.where(numbers > 5 ,numbers*2 , numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


In [ ]:
# where clause executes the above statement like this 
if(numbers > 5):
    numbers*2
else:
    numbers


## Adding and Removing Data

In [8]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

sum = arr1+ arr2 
print(sum)

combined = np.concatenate((arr1 , arr2))
print(combined)


[5 7 9]
[1 2 3 4 5 6]


## Array Compatibility 

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,10])

print("Compatibility shapes" , a.shape == b.shape)
print("Compatibility shapes" , a.shape == c.shape)


Compatibility shapes True
Compatibility shapes False


## Adding new Row and Col

In [13]:
original = np.array([[1,2] , [3,4]])
new_row = np.array([5,6])

# vstack is used to add a row 
with_new_row = np.vstack((original , new_row))
print(original)
print('\n')
print(with_new_row)

new_col = np.array([[7] , [8]])
with_new_col = np.hstack((original , new_col))
print(with_new_col)

[[1 2]
 [3 4]]


[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


## Delete

In [14]:
arr = np.array([1,2,3,4,5])
# here deleted array is returned instead of the deleted value 
deleted = np.delete(arr , 2)
print(deleted)

[1 2 4 5]
