In [1]:
import numpy as np

# Army strength (in thousands) in 3 regions over 4 months
data = np.array([[50, 55, 60, 58],
                 [40, 42, 44, 43],
                 [70, 72, 75, 78]])

# Tasks:
# 1. Print total soldiers in each month
# 2. Average strength of each region
# 3. Month with highest total strength
# 4. Which region had most growth?
# 5. Add 5% reinforcement to all numbers (use broadcasting)


#  Print total soldiers in each month

In [ ]:
for i in range(3):
    print(sum(data[i]))

total = np.sum(data[: , :] , axis =1)
print(total) 

223
169
295
[223 169 295]


# Average strength of each region

In [7]:
total = np.average(data[: , :] , axis =1)
print(total) 

[55.75 42.25 73.75]


# Month with highest total strength

In [9]:
monthly_totals = np.sum(data, axis=0)
max_month_index = np.argmax(monthly_totals)
print(f"Month {max_month_index + 1} has the highest total strength: {monthly_totals[max_month_index]}k soldiers")


Month 3 has the highest total strength: 179k soldiers


# Which region had most growth?

In [10]:
growth = data[:, -1] - data[:, 0]
print("Growth for each region:", growth)

# Find the region with the most growth:
max_growth_index = np.argmax(growth)
print(f"Region {max_growth_index + 1} had the highest growth: {growth[max_growth_index]}k soldiers")


Growth for each region: [8 3 8]
Region 1 had the highest growth: 8k soldiers


# Add 5% reinforcement to all numbers (use broadcasting)

In [11]:
reinforced_data = data * 1.05
print(reinforced_data.astype(int)) 


[[52 57 63 60]
 [42 44 46 45]
 [73 75 78 81]]
