In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### Difference between List and Array(numpy)

In [4]:
py_list = [1,2,3]
print("Python list multiplication" , py_list*2)

np_array = np.array([1,2,3])
print("Python array multiplication" , np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("/n List operation time:" , time.time() - start)

start = time.time()
np_array = np.arange(1000000)*2
print("/n Numpy operation time:" , time.time() - start)


Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]
/n List operation time: 0.08037090301513672
/n Numpy operation time: 0.007529735565185547


## Creating Array from Scratch


In [8]:
zeroes = np.zeros((3,4))
print("Zeros array: \n",zeroes)

ones = np.ones((3,4))
print("Ones array: \n",ones)

full = np.full((2,2),7)
print("Full array: \n",full)

random = np.random.random((2,3))
print(random)

seq1 = np.arange(0,10)
print(seq1)

seq2 = np.arange(0,10,2)
print(seq2)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array: 
 [[7 7]
 [7 7]]
[[0.35522921 0.45991026 0.15217126]
 [0.92644781 0.99714479 0.82009725]]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


## Vector , Matrix and tensor 


In [10]:
vector = np.array([1,2,3])
print('Vector:\n',vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix:", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor \n",tensor)


Vector:
 [1 2 3]
Matrix: [[1 2 3]
 [4 5 6]]
tensor 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties 

In [11]:
arr = np.array([[1,2,3],[4,5,6]])

print("Shape" , arr.shape)
print("Dimension" , arr.ndim)
print("Size" , arr.size)
print("Dtype" , arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
Dtype int64


## Array Reshaping 

In [15]:
arr = np.arange(12)
print("Original Array" , arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped Array" , reshaped)

flattened = reshaped.flatten()
print(flattened)

# reval return view instead of copy 
reveled = reshaped.ravel()
print(reveled)

# transpose
transposr = reshaped.T
print(transposr)


Original Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
